### PR TITLE
Bugs/oai getrecord visibility

### PR DESCRIPTION
**Pull request by okeen**

### CODE REVIEW

**Comment by cjcolvar** [comment]
I think this can be closed because https://github.com/projectblacklight/blacklight_oai_provider/pull/28 was merged and version 6.1.1 released.  @okeen do you agree?

**Comment by okeen** [comment]
Yes, but I like the test cases that we added here. Do you think it's worth integrating them on the main branch?

**Comment by cjcolvar** [comment]
Sure, I forgot that there were tests added.  More tests are good.

**Comment by okeen** [comment]
OK, I've added the tests into https://github.com/ubiquitypress/hyku_addons/pull/96. Closing this one

**Pull request closed without merging**
